<?php

namespace App\Helpers;

class CanalesHelper
{
    public static function getLista(): array
    {
        // Lista extraída del PDF "CANALES MONTERIA.pdf"
        // Formato: 'Nombre Canal' => 'Numero: Nombre Canal'
        return [
            'Cartoon Network HD' => '1: Cartoon Network HD',
            'Senal Colombia HD' => '2: Senal Colombia HD',
            'Tooncast' => '3: Tooncast',
            'Cartoonito' => '4: Cartoonito',
            'Intalnet TV' => '5: Intalnet TV',
            'Telecaribe' => '6: Telecaribe',
            'Baby TV' => '7: Baby TV',
            'Nickelodeon' => '8: Nickelodeon',
            'Teen Nick' => '9: Teen Nick',
            'Nick Jr' => '10: Nick Jr',
            'CANAL 1' => '11: CANAL 1',
            'RCN HD' => '12: RCN HD',
            'Caracol HD' => '13: Caracol HD',
            'Disney Channel' => '14: Disney Channel',
            'Discovery Kids' => '15: Discovery Kids',
            'Animal Planet HD' => '16: Animal Planet HD',
            'Disney Jr' => '17: Disney Jr',
            'National Geographic' => '18: National Geographic',
            'Discovery Science' => '19: Discovery Science',
            'Discovery H&H HD' => '20: Discovery H&H HD',
            'Discovery Turbo' => '21: Discovery Turbo',
            'Golden Edge' => '22: Golden Edge',
            'Paramount HD' => '23: Paramount HD',
            'Discovery HD' => '24: Discovery HD',
            'Cinecanal' => '25: Cinecanal',
            'STAR CHANNEL HD' => '26: STAR CHANNEL HD',
            'TNT' => '27: TNT',
            'TNT Series HD' => '28: TNT Series HD',
            'OROMAR TV' => '29: OROMAR TV',
            'Adult Swim HD' => '30: Adult Swim HD',
            'FX' => '31: FX',
            'Golden Latino' => '32: Golden Latino',
            'Space HD' => '33: Space HD',
            'MTV' => '34: MTV',
            'HTV' => '35: HTV',
            'HGTV' => '36: HGTV',
            'Food Network HD' => '37: Food Network HD',
            'Comedy Central HD' => '38: Comedy Central HD',
            'TNT Novelas' => '39: TNT Novelas',
            'Las Estrellas' => '40: Las Estrellas',
            'ABN' => '41: ABN',
            'Enlace' => '42: Enlace',
            'EWTN' => '43: EWTN',
            'Cristovision' => '44: Cristovision',
            'Distrito Comedia' => '45: Distrito Comedia',
            'Univision Latino' => '46: Univision Latino',
            'TL Novelas' => '47: TL Novelas',
            'Mariavision' => '48: Mariavision',
            'ESPN HD' => '49: ESPN HD',
            'ESPN 2 HD' => '50: ESPN 2 HD',
            'ESPN 3' => '51: ESPN 3',
            'ESPN 4 HD' => '52: ESPN 4 HD',
            'ESPN 5 HD' => '53: ESPN 5 HD',
            'ESPN 6' => '54: ESPN 6',
            'ESPN 7' => '55: ESPN 7',
            'Telepacifico' => '56: Telepacifico',
            'TRO' => '57: TRO',
            'Teleantioquia' => '58: Teleantioquia',
            'City TV' => '59: City TV',
            'CANAL INSTITUCIONAL' => '60: CANAL INSTITUCIONAL',
            'Canal del Congreso' => '61: Canal del Congreso',
            'Trece' => '62: Trece',
            'Zoom' => '63: Zoom',
            'Teleislas' => '64: Teleislas',
            'Canal Capital' => '65: Canal Capital',
            'Telecafe' => '66: Telecafe',
            'Telesur' => '67: Telesur',
            'Latina HD' => '68: Latina HD',
            'DW' => '69: DW',
            'USA' => '70: USA',
            'Bandamax' => '71: Bandamax',
            'Sony Movies' => '72: Sony Movies',
            'RCN HD (Dup)' => '73: RCN HD',
            'CARACOL TV HD' => '74: CARACOL TV HD',
            'AXN HD' => '75: AXN HD',
            'Sony HD' => '76: Sony HD',
            'UNIVERSAL CHANNEL HD' => '77: UNIVERSAL CHANNEL HD',
            'Studio Universal HD' => '78: Studio Universal HD',
            'E! HD' => '79: E! HD',
            'De Pelicula' => '80: De Pelicula',
            'Telemundo' => '81: Telemundo',
            'History Channel HD' => '82: History Channel HD',
            'History 2 HD' => '83: History 2 HD',
            'Lifetime' => '84: Lifetime',
            'CNN' => '85: CNN',
            'Discovery ID' => '86: Discovery ID',
            'Hola! TV' => '87: Hola! TV',
            'Sun Channel' => '88: Sun Channel',
            'Discovery World HD' => '89: Discovery World HD',
            'Discovery Theater' => '90: Discovery Theater',
            'A&E' => '91: A&E',
            'TLC' => '92: TLC',
        ];
    }
}